---
- hosts: ca_ssh_clients
  remote_user: ubuntu
  become: true
  tasks:
    - name: copy over ca-cert file needed to talk to vault
      copy:
        src: /Users/ashishbaiju/.certauth/insightab/ca_public_key.pem
        dest: /tmp/ca_public_key.pem
    - name: update files on the ssh ca clients
      script: /Users/ashishbaiju/Documents/git-repos/git-ssh-with-vault/terraform-aws-ssh-clients/ansible/scripts/ca-userdata.sh
